version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=generateur
      - MYSQL_USER=exo_generateur
      - MYSQL_PASSWORD=1234
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: generateur
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=generateur
      - MYSQL_USER=exo_generateur
      - MYSQL_PASSWORD=1234
volumes:
  generateur: